---
# - name: Wait for port 22 to become open and contain "OpenSSH"
#   hosts: aws_ec2
#   gather_facts: False
#   tasks:
#     - name: Ensure ssh port is open
#       wait_for:
#         port: 22
#         host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
#         search_regex: OpenSSH
#         delay: 10
#       vars:
#         ansible_connection: local

- name: Install Docker, Docker-compose & Python3
  hosts: tag_Name_dev_server
  become: yes
  gather_facts: False
  tasks:

    - name: Install docker & python
      yum:
        name:
          - docker
          - python3
          - python3-pip
        update_cache: yes
        state: latest

    - name: Install Docker-compose
      get_url: 
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x
     
    - name: Verify installation
      command: docker-compose --version

    - name: Start docker daemon
      systemd:
        name: docker
        state: started

    # - name: Install docker python module
    #   pip:
    #     name: 
    #       - docker
    #       - docker-compose

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Reconnect to server session
      meta: reset_connection

- name: Start docker container
  hosts: tag_Name_dev_server
  vars_files:
    - project-vars
  tasks:

    - name: Copy docker compose
      copy:
        src: /Users/moabdulhadi/Documents/School/DevOps/bootcamp-projects/Ansible/docker-compose-full.yaml
        dest: /home/ec2-user/docker-compose.yaml

    - name: Docker login
      docker_login: 
        registry_url: https://index.docker.io/v1/
        username: moyvr
        password: "{{docker_password}}"

    - name: Start container from compose
      # docker_compose: 
      #   project_src: /home/ec2-user
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user
